### ISSUE TITLE
Bug found with wget

### ISSUE THREAD

**Issue by etmclovin** [AaronF86/VScode-syrupmode#5]
**Describe the bug**
A weird error message occurs when running the install syrup command

**To Reproduce**
1. Run Install Syrup
2. Observe odd error message

**Expected behavior**
Syrup to be installed

**Screenshots**
error message:
![image](https://github.com/user-attachments/assets/67c0001e-7b6f-406e-9599-03530009d024)
proof i have wget
![image](https://github.com/user-attachments/assets/1af4c6ed-73c6-4549-bb1c-77cc33cd97dd)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 11

**Additional context**
This happened while i was trying to fix my code snippets, i realised it relys on the `editor.tabcompletion`  setting being set to "onlySnippets" so i tried to amend a line in the install syrup command that would change the setting upon running so that if the user didnt have it on they would still be able to use code snippets
![image](https://github.com/user-attachments/assets/d9f44adb-1e51-472f-b1cd-5cd4f1c1f98a)
however i did try removing this line in the off chance it created the issue, it did not

**Comment by etmclovin** [comment]
good chance this is all my end also, lmk if it is and ill pr the change for the settings update

**Comment by AaronF86** [comment]
This is a known issue the wget command is not installed as part of windows by default

**Comment by etmclovin** [comment]
ah ok ill make that pr then if its all good
